### PR TITLE
Support specifying the threshold

### PR DESCRIPTION
**Pull request by nickknissen**
With inspiration from @d1manson issue #8

### CODE REVIEW

**Comment by nickknissen** [comment]
@Akryum Should we consider this repository dead and fork it?

**Comment by lukeheath** [comment]
This feature would be helpful.

**Comment by jpt** [comment]
@Akryum Any update on this? Very useful PR from @nickknissen

**Comment by lukeheath** [comment]
@GitCash please send @nickknissen 2500 bits to say thanks for the feature!

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/nickknissen)
@nickknissen

**Comment by lukeheath** [comment]
@GitCash please send @Akryum 2500 bits to say thanks for this project!

**Comment by GitCash** [comment]
[GitCash Tip Response](https://gitcash.io/claim/Akryum)
@Akryum

**Comment by Akryum** [comment]
Thanks @lukeheath 😸

**Pull request merged**
